angular-build:
  before_script:
    - 'docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY'
  image: 'docker:latest'
  script:
    - 'cd spi-frontend && docker image build --tag registry.gitlab.com/13_mark/spi-bet-prediction/spi-soccer-prediction-frontend:latest .'
    - 'docker push registry.gitlab.com/13_mark/spi-bet-prediction/spi-soccer-prediction-frontend:latest'
  services:
    - 'docker:dind'
  stage: build

backend-build:
  before_script:
    - 'docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY'
  image: 'docker:latest'
  script:
    - 'cd spi-backend && docker image build --tag registry.gitlab.com/13_mark/spi-bet-prediction/spi-soccer-prediction-backend:latest .'
    - 'docker push registry.gitlab.com/13_mark/spi-bet-prediction/spi-soccer-prediction-backend:latest'
  services:
    - 'docker:dind'
  stage: build

console-app-build:
  before_script:
    - 'docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY'
  image: 'docker:latest'
  script:
    - 'cd spi-console-app && docker image build --tag registry.gitlab.com/13_mark/spi-bet-prediction/spi-soccer-prediction-console-app:latest .'
    - 'docker push registry.gitlab.com/13_mark/spi-bet-prediction/spi-soccer-prediction-console-app:latest'
  services:
    - 'docker:dind'
  stage: build
